# Service
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-svc
spec:
  selector:
    app: java-app
  ports:
   - protocol: TCP
     port: 80

# Service-NodePort/LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
 name: java-app-svc-nodeport
spec:
 selector:
   app: java-app
 # type: LoadBalancer
 type: NodePort
 ports:
  # the port that this service should serve on
  - protocol: TCP
    port: 80

# Deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: kota661/java-helloworld:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
