# Service
---
apiVersion: v1
kind: Service
metadata:
 name: {FullName}
spec:
 selector:
   app: java-app
   version: "{Version}"
 # type: LoadBalancer
 type: NodePort
 ports:
  # the port that this service should serve on
  - protocol: TCP
    port: 80
    targetPort: 80
    # nodePort: 30000-32767

# Deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {FullName}
spec:
  replicas: {Replicas}
  template:
    metadata:
      labels:
        app: java-app
        version: "{Version}"
    spec:
      containers:
      - name: java-app
        image: {DockerImage}
        #@param Always, Never, default:IfNotPresent
        #imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        #readinessProbe:
        #  httpGet:
        #    path: /healthz
        #    port: 8080
        #  initialDelaySeconds: 3
        #  periodSeconds: 3
        #  timeoutSeconds: 1
        #  failureThreshold: 3
        #livenessProbe:
        #  httpGet:
        #    path: /ready
        #    port: 8080
        #  initialDelaySeconds: 30
        #  timeoutSeconds: 1
        #  periodSeconds: 20
        #  failureThreshold: 3
        #resources:
        #  requests:
        #    cpu: 100m
        #    memory: 100Mi
